modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"
displayTest="IGNORE_SERVER_VERSION"

[[mods]]
modId="justenoughserverlessrecipes"
version="${version}"
displayName="Just Enough Serverless Recipes"
license="The GNU General Public License (GPL-3.0)"
authors="Draconic Velum"
description='''
Provides vanilla JEI recipes on servers without JEI installed.
'''

[[dependencies.justenoughserverlessrecipes]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.justenoughserverlessrecipes]]
modId="jei"
type="required"
versionRange="[29.2.0.20,)"
ordering="NONE"
side="CLIENT"
